global:
  ssl:
    enabled: ${ssl_enabled}
    clusterIssuer: ${cluster_issuer}
  endpoints:
    networkName: ${name}
    networkShortName: ${short_name}
    deployment:
      domain: ${deployment_domain_name}
    aggregate:
      domain: ${aggregate_domain_name}

backends:
  websockets:
    upstreamServer:
      uri: ${ws_upstream_uri}
      port: ${ws_upstream_port}
  jsonRPC:
    upstreamServer:
      uri: ${rpc_upstream_uri}
      port: ${rpc_upstream_port}
  healthCheck:
    upstreamServer:
      uri: ${health_upstream_uri}
      port: ${health_upstream_port}